<?php
/**
 * EntityCategory
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FiwooDeviceManagement
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0-development
 * Contact: info@fiwoo.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.40
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * EntityCategory Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EntityCategory
{
    /**
     * Possible values of this enum
     */
    const LUMINAIRE = 'LUMINAIRE';
const WASTE_CONTAINER = 'WASTE_CONTAINER';
const WEATHER_STATION = 'WEATHER_STATION';
const ENVIRONMENTAL_QUALITY = 'ENVIRONMENTAL_QUALITY';
const GPS = 'GPS';
const PARKING = 'PARKING';
const ELECTRIC_PANEL = 'ELECTRIC_PANEL';
const HEALTH = 'HEALTH';
const VIDEO_CAMERA = 'VIDEO_CAMERA';
const ELECTRIC_METER = 'ELECTRIC_METER';
const WATER_METER = 'WATER_METER';
const IRRIGATION = 'IRRIGATION';
const OTHER = 'OTHER';
const UNKNOWN = 'UNKNOWN';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LUMINAIRE,
self::WASTE_CONTAINER,
self::WEATHER_STATION,
self::ENVIRONMENTAL_QUALITY,
self::GPS,
self::PARKING,
self::ELECTRIC_PANEL,
self::HEALTH,
self::VIDEO_CAMERA,
self::ELECTRIC_METER,
self::WATER_METER,
self::IRRIGATION,
self::OTHER,
self::UNKNOWN,        ];
    }
}
