<?php
/**
 * DevicesAuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FiwooDeviceManagement
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0-development
 * Contact: info@fiwoo.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.40
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DevicesAuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DevicesAuthApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAuthDevice
     *
     * .
     *
     */
    public function testCreateAuthDevice()
    {
    }

    /**
     * Test case for deleteAllAuthDevices
     *
     * .
     *
     */
    public function testDeleteAllAuthDevices()
    {
    }

    /**
     * Test case for deleteAuthDevice
     *
     * .
     *
     */
    public function testDeleteAuthDevice()
    {
    }

    /**
     * Test case for readAuthDevice
     *
     * .
     *
     */
    public function testReadAuthDevice()
    {
    }

    /**
     * Test case for renewDeviceToken
     *
     * .
     *
     */
    public function testRenewDeviceToken()
    {
    }
}
