<?php
/**
 * TemplatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FiwooDeviceManagement
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0-development
 * Contact: info@fiwoo.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TemplatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for countDevicesTemplate
     *
     * .
     *
     */
    public function testCountDevicesTemplate()
    {
    }

    /**
     * Test case for createTemplate
     *
     * .
     *
     */
    public function testCreateTemplate()
    {
    }

    /**
     * Test case for deleteTemplate
     *
     * .
     *
     */
    public function testDeleteTemplate()
    {
    }

    /**
     * Test case for listAllTemplates
     *
     * .
     *
     */
    public function testListAllTemplates()
    {
    }

    /**
     * Test case for listMineTemplates
     *
     * .
     *
     */
    public function testListMineTemplates()
    {
    }

    /**
     * Test case for listPublicTemplates
     *
     * .
     *
     */
    public function testListPublicTemplates()
    {
    }

    /**
     * Test case for readTemplate
     *
     * .
     *
     */
    public function testReadTemplate()
    {
    }

    /**
     * Test case for updateTemplate
     *
     * .
     *
     */
    public function testUpdateTemplate()
    {
    }
}
